name: Cheesecom
favicon: null
layout_spectrum: 0.7711774609051645
typography_spectrum: 0.8779959999956191
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.571318170754239
  lightness: 0.14311284804716706
  saturation: 0.4117388306185603
  rhythmicContrast: 0.1545179293025285
purpose: []
